name: Get Citation Data

on: 
 push:
   branches: [main]
 page_build: 
 schedule:
  - cron:  '0 8 * * *'
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: true
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        pip install requests
    - name: Run
      run: |
        cd ./google_scholar_crawler
        mkdir -p results
        python fix_scholar_data.py
        ls -la results/
        cd results
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # 创建新的临时目录用于保存结果
        mkdir -p ${GITHUB_WORKSPACE}/temp_branch
        cp *.json ${GITHUB_WORKSPACE}/temp_branch/
        
        # 检出google-scholar-stats分支
        cd ${GITHUB_WORKSPACE}
        git fetch --all
        git checkout -B google-scholar-stats || git checkout --orphan google-scholar-stats
        git rm -rf . || true
        git clean -fdx || true
        
        # 复制结果文件并提交
        cp -r ${GITHUB_WORKSPACE}/temp_branch/* .
        git add *.json
        git commit -m "Updated Citation Data" || echo "No changes to commit"
        git push origin google-scholar-stats
